default_platform(:ios)

before_all do
  create_keychain(
    name: "keychain",
    password: "password",
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
  match(type: "appstore", keychain_name: "keychain", keychain_password: "password", readonly: true)
end


platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do |options|
    # Increment build number
    increment_build_number(xcodeproj: "Facto.xcodeproj")
    
    # Build the app
    build_app(
      scheme: "Facto",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "dev.draft.Facto" => "Facto Distribution"
        }
      }
    )

    api_key = app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_filepath: File.absolute_path("tmp/AuthKey.p8"),
      duration: 1200,
      in_house: false
    )
        
    # Upload to TestFlight
    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
    
  end
end